import React from "react";
import { Poppins } from "next/font/google";

import "@/app/globals.css";
import { AsideBar, NavBar } from "@/components";
const poppins = Poppins({ subsets: ["latin"], variable: "--font-poppins", weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CustomLayout = ({ children }: { children: React.ReactNode }) => {
  
  return (
    <>
      <NavBar />
      <AsideBar />

      <div className=" px-10 sm:ml-64 ">
        <div className="page-container p-4 border-2 rounded-lg">{children}</div>
      </div>
    </>
  );
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={poppins.className}>
      <CustomLayout>{children}</CustomLayout>
    </body>
  </html>
);

export default RootLayout;
