import React from "react";
import { Inter } from "next/font/google";
import "flowbite";

import StyledComponentsRegistry from "./antdRegistry";
import "@/app/globals.css";
import { AsideBar, NavBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CustomLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <NavBar />
      <AsideBar />
      <div className=" px-10 sm:ml-64 ">
        <div className="page-container p-4 border-2 rounded-lg">{children}</div>
      </div>
    </>
  );
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <CustomLayout>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </CustomLayout>
    </body>
  </html>
);

export default RootLayout;
