version: '3.8'
services:
  postgres:
    build: ./database
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: