# Use Node.js image
FROM node:20.5.1

# Set working directory
WORKDIR /usr/backend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3001

# Run the application
CMD ["npm", "run", "start:dev"]
